<?php

/**
 * Default Layout
 *
 * @author
 * @version
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype()
?>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php
echo $this->placeholder('css'),"\n";
echo $this->headTitle(),"\n";
// echo $this->placeholder('js');
// echo $this->headScript();
// echo $this->headStyle();
?>
</head>
<body>
<?php echo $this->layout()->content ?>
</body>
</html>
