<?php

/**
 * Default Layout
 *
 * @author
 * @version
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype()
?>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php
// echo $this->headTitle();
// echo $this->placeholder('css');
// echo $this->placeholder('js');
// echo $this->headScript();
// echo $this->headStyle();
?>
</head>
<body>
  <h1><?php echo $this->placeholder('title'); ?></h1>
  <?php echo $this->layout()->content ?>
</body>
</html>
